In [2]:
import numpy as np

In [2]:
def grad(x):
    return 2*x+5*np.cos(x)

In [3]:
def cost(x):
    return x*2+5*np.sin(x)

In [4]:
def myGD1(x0, eta):
    x=[x0]
    for it in range(100):
        x_new=x[-1] - eta*grad(x[-1])
        if abs(grad(x_new))< le-3:
            break;
        x.append(x_new)
    return(x,it)

-------------------------

In [20]:
x= np.arange(2,10)

np.arange?
x,x.reshape(-1,2)

(array([2, 3, 4, 5, 6, 7, 8, 9]),
 array([[2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

In [11]:
from sklearn.linear_model import LinearRegression
import numpy as np
X= np.random.rand(1000);
y = 4 + 3 * X + .5*np.random.randn(1000) # noise added
a = np.arange(2,10)

In [25]:
# Building Xbar 
one = np.ones((X.shape[0],1))
Xbar = np.concatenate((one, X.reshape(-1, 1)), axis = 1)
Xbar, Xbar.T

(array([[1.        , 0.81799266],
        [1.        , 0.80859108],
        [1.        , 0.51629609],
        ...,
        [1.        , 0.31703514],
        [1.        , 0.49547804],
        [1.        , 0.09145985]]),
 array([[1.        , 1.        , 1.        , ..., 1.        , 1.        ,
         1.        ],
        [0.81799266, 0.80859108, 0.51629609, ..., 0.31703514, 0.49547804,
         0.09145985]]))

In [22]:
def grad(w):
    N = Xbar.shape[0]
    return 1/N * Xbar.T.dot(Xbar.dot(w) - y)