In [2]:
import sys
import numpy as np



In [11]:
3**6 #Mũ

729

## Basic Numpy Array

In [13]:
np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [15]:
A= np.arange(0, 10,dtype= np.int32) #numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)

In [16]:
print(A)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
A[0:] #[start:end:step]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
A[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
A[2:3]

array([2])

In [20]:
A[2:1]

array([], dtype=int32)

In [21]:
A[4:1]

array([], dtype=int32)

In [22]:
A[2:4]

array([2, 3])

In [24]:
B=[range(i,i+3) for i in [2,4,6]]

In [25]:
print(B)

[range(2, 5), range(4, 7), range(6, 9)]


In [26]:
print(B[0])

range(2, 5)


## Array Types

In [5]:
a=np.array([1,2,3,6], dtype='float')

In [28]:
np.array([2], dtype= np.float64).dtype

dtype('float64')

In [30]:
np.array(['a'], dtype=np.string_).dtype

dtype('S1')

In [31]:
np.array(['abc']).dtype

dtype('<U3')

In [32]:
np.array(['abcd']).dtype

dtype('<U4')

In [8]:
b= np.array([6,8,9], dtype= np.int32)

In [7]:
a.dtype

dtype('float64')

In [9]:
b.dtype

dtype('int32')

## Demensions and shapes

In [33]:
A= np.array([
    [1,6,5],
    [5,9,8]
])

In [34]:
print(A)

[[1 6 5]
 [5 9 8]]


In [35]:
A.shape

(2, 3)

In [36]:
A.ndim

2

In [37]:
A.size

6

In [38]:
A.dtype

dtype('int32')

## Indexing and slicing of matrices

In [56]:
A= np.array([
    np.arange(1,4),
    np.arange(4,7),
    np.arange(7,10),
])

In [57]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Summary Statistics

In [58]:
A= np.array([
    np.arange(1,4),
    np.arange(4,7),
    np.arange(7,10),
])

In [59]:
A= np.array([
    np.arange(1,4),
    np.arange(4,7),
    np.arange(7,10),
])

In [60]:
A.sum()

45

In [61]:
A.mean()

5.0

In [62]:
A.std()

2.581988897471611

In [63]:
A.sum(axis=0)

array([12, 15, 18])

In [64]:
A.sum(axis=1)

array([ 6, 15, 24])

In [65]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

## Boarcasting and vectorized operations

In [70]:
A= np.arange(4)

In [71]:
print(A)

[0 1 2 3]


In [72]:
A*10

array([ 0, 10, 20, 30])

In [76]:
>=2

array([False,  True,  True,  True])

In [74]:
B= [i*100 for i in A]

In [75]:
print(B)

[0, 100, 200, 300]


### `eye`, `empty`

In [73]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])