In [1]:
#numpy là 1 thư viện toán học phổ biến
#cho phép làm việc với các mảng, ma trận đa chiều


# NUMPY

### Import

In [3]:
import numpy as np

### Create np array from python list

In [5]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [6]:
[3.14,4,5,"string"]

[3.14, 4, 5, 'string']

In [13]:
np.array([3.14,4,5,"string"])
#np.array([3.14,4,5,4])
# np sẽ tự động convert từ datatype thấp hơn sang cao hơn
# chuyển về theo phần từ cao nhất trong list
#nếu có datatype 'string' => chuyển hết về string

array(['3.14', '4', '5', 'string'], dtype='<U32')

In [14]:
np.array([3.14,4,5,7], dtype='float32')
#bắt buộc chuyển về theo một DT mình muốn, nếu bắt string chuyển về thì báo lỗi

array([3.14, 4.  , 5.  , 7.  ], dtype=float32)

In [17]:
a1=np.array([4,2,9,8])
type(a1)

numpy.ndarray

In [28]:
a2=np.array([[3,4,5],
             [8,8,4]]) #mảng 2 chiều
type(a2)

numpy.ndarray

In [29]:
a2.shape

(2, 3)

In [33]:
print(a1.ndim)  #in ra số chiều
print(a2.ndim)
print(a2.dtype) #DT của phần tử bên trong
print(a2.size)  #số phần tử

1
2
int32
6


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)
## Creating Arrays from Scratch
### `zeros`, `ones`, `full`, `arange`, `linspace`

In [45]:
zeros_array=np.zeros((3,4), dtype=int,) #tạo một array toàn số 0
print(zeros_array)
print(zeros_array.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [47]:
ones_array=np.ones((3,4), dtype=int,) #tạo một array toàn số 1
print(ones_array)
print(ones_array.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32


In [58]:
#numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None) những thằng []: optional
arange_array= np.arange(2,9,2)
print(arange_array)

[2 4 6 8]


In [55]:
# numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)[source]
full_array= np.full((2,9), 5) # một array full số theo ý
print(full_array)

[[5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5]]


In [61]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
# tạo ra một array tuyến tính với khoảng cách nhưu yêu cầu
linspace_array= np.linspace(0,2,5)
print(linspace_array)

[0.  0.5 1.  1.5 2. ]


### `Random`

In [62]:
# tạo ra array với thành phần ngẫu nhiên
np.random.random((4,5))

array([[0.32553083, 0.2977306 , 0.3782234 , 0.46251821, 0.00245248],
       [0.22687432, 0.89337196, 0.48932274, 0.91886721, 0.49326318],
       [0.6895624 , 0.76487701, 0.55256581, 0.91772946, 0.79032766],
       [0.81892682, 0.43880217, 0.93605736, 0.11389971, 0.89473865]])

In [65]:
# seed
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [66]:
np.random.normal(0,1, (3,3)) #mean: 0: gtri trung bình,  1: standard deviation: độ lệch chuẩn

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [69]:
np.random.randint(0,10,(4,5))

array([[5, 9, 4, 4, 6],
       [4, 4, 3, 4, 4],
       [8, 4, 3, 7, 5],
       [5, 0, 1, 5, 9]])

In [70]:
np.random.rand(4,4)

array([[0.94957105, 0.66252687, 0.01357164, 0.6228461 ],
       [0.67365963, 0.971945  , 0.87819347, 0.50962438],
       [0.05571469, 0.45115921, 0.01998767, 0.44171092],
       [0.97958673, 0.35944446, 0.48089353, 0.68866118]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Indexing & Slicing
### One-dimensional subarray

In [75]:
x1= np.random.randint(20, size=6)
x1

array([ 3,  3, 18, 14,  3, 17])

In [79]:
x1[4], x1[-1] #-1: cuối cùng

(3, 17)

In [81]:
x2= np.random.randint(10, size=(3,4))
x2

array([[6, 3, 3, 8],
       [8, 8, 2, 3],
       [2, 0, 8, 8]])

In [82]:
x2[2,1]

0

In [83]:
x2[2,1]=9
x2

array([[6, 3, 3, 8],
       [8, 8, 2, 3],
       [2, 9, 8, 8]])

In [86]:
x1[0:3] #cắt

array([ 3,  3, 18])

In [88]:
x1[1:4]

array([ 3, 18, 14])

In [89]:
x1[::2] #step

array([ 3, 18,  3])

In [90]:
x2[:2, :3]

array([[6, 3, 3],
       [8, 8, 2]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Reshaping of array & Transpose

In [94]:
grid=np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
x= np.array([1,2,3])
x.shape

(3,)

In [98]:
x.reshape((1,3)).shape

(1, 3)

In [100]:
x= np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
x.T 
# đổi hàng thành cột, cột thành hàng

array([[1, 4],
       [2, 5],
       [3, 6]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Concatenation and Splitting

In [106]:
# nối và cắt array

In [110]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [113]:
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [115]:
grid=np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
np.concatenate((grid, grid), axis=1) #nối theo chiều dọc


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [126]:
#vstack
x=np.array([1,2,3])
grid=np.array([[4,5,6],[7,8,9]])

In [123]:
np.vstack((x, grid)) #vertical stack

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
#horizontal stack
y= np.array([[4],[8]])
np.hstack((y, grid))

array([[4, 4, 5, 6],
       [8, 7, 8, 9]])

In [131]:
x=np.array([1,5,4,7,8,9,5,4,1,2,6])
x

array([1, 5, 4, 7, 8, 9, 5, 4, 1, 2, 6])

In [133]:
x1,x2,x3=np.split(x, [3,5])
x1,x2,x3

(array([1, 5, 4]), array([7, 8]), array([9, 5, 4, 1, 2, 6]))

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.

![image-broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [135]:
a= np.arange(3)
a

array([0, 1, 2])

In [137]:
a+5 #broadcasting

array([5, 6, 7])

In [139]:
b= np.ones((3,3))
a.shape, b.shape

((3,), (3, 3))

In [140]:
a+b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [141]:
a*b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [153]:
x1=np.arange(3)
x1=x1.reshape((3,1))
x1.shape

(3, 1)

In [152]:
x2=np.arange(3)
x2
x2.shape

(3,)

In [154]:
x1+x2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Manipulating & Comparing Arrays

### Aggregation

In [156]:
list_number=[1,2,3]

In [158]:
ll=np.array(list_number)
ll

array([1, 2, 3])

In [159]:
sum(ll) #python sum() not of numpy

6

In [161]:
np.sum(ll) #numpy sum()

6

In [169]:
massive_array=np.random.random(10000)
print(massive_array[:5])
print(massive_array.size)
print(massive_array.shape)

[0.83579875 0.84884747 0.59216885 0.84214393 0.48425841]
10000
(10000,)


In [170]:
# so sánh thời gian chạy giữa một thằng built-in của python và thằng của numpy
%timeit sum(massive_array) 
%timeit np.sum(massive_array)
# kết quả:
# 1.24 ms ± 161 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
# 12.3 µs ± 1.06 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

1.24 ms ± 161 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
12.3 µs ± 1.06 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [172]:
#giá trị trung bình (mean)
np.mean(massive_array)

0.49864628215170986

In [175]:
np.max(massive_array)

0.9999484968692297

In [176]:
np.min(massive_array)

0.00019681476404465048

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Standard Deveation & Variance
### (Độ Lệch Chuẩn & Phương Sai)

### Aggregation (Standard Deviation is a measure of how spread out numbers are.)

In [177]:
# là kích thước đo độ phân tán so với giá trị min
# Ký hiệu: Its symbol is σ (the greek letter sigma)
# The formula is easy: it is the square root of the Variance (căn bậc 2 của phương sai)

### Variance (The average of the squared differences from the Mean.)

In [ ]:
# (lấy từng giá trị dataPoint trừ giá trị trung bình và bình phương lên), cuối cùng lấy trung bình

## Example

![image-broadcasting](https://www.mathsisfun.com/data/images/statistics-dogs-graph.gif)

In [185]:
statistics_dogs_array=np.array([600, 470, 170, 430, 300])
print("statistics_dogs_array: {}".format(statistics_dogs_array))
# đầu tin tìm giá trị trung bình (mean)
print("mean: {}".format(np.mean(statistics_dogs_array)))

statistics_dogs_array: [600 470 170 430 300]
mean: 394.0


![image-dogs](https://www.mathsisfun.com/data/images/statistics-dogs-mean.gif)

### tiếp: tính sự khách biệt / độ chênh lệch (differences) giữa chiều cao thật và mean
![image-broadcasting](https://www.mathsisfun.com/data/images/statistics-dogs-deviation.gif)

In [191]:
# Variance
# σ2 = 2062 + 762 + (−224)2 + 362 + (−94)25 
#    = 42436 + 5776 + 50176 + 1296 + 88365 
#    = 1085205 
#    = 21704
print("Variance: {}".format(np.var(statistics_dogs_array))) 

#lấy bình phương của (giá trị thật của các dataPoint trừ đi mean), sau đó lấy trung bình
#So the Variance is 21704
#-*-*-*-*-*-*-----------------------------------------------------------------------------
# And the Standard Deviation is just the square root of Variance, so:
# Standard Deviation
# σ= √21704
#  = 147.32...
#  = 147 (to the nearest mm)
print("Standard Deviation: {}".format(np.std(statistics_dogs_array))) 
print("Standard Deviation: {}".format(np.sqrt(np.var(statistics_dogs_array)))) 

Variance: 21704.0
Standard Deviation: 147.32277488562318
Standard Deviation: 147.32277488562318


![image-dogs](https://www.mathsisfun.com/data/images/statistics-standard-deviation.gif)

In [187]:
# kẻ thêm 2 đường cách mean 147mm => độ lệch chuẩn của dữ liệu
# So, using the Standard Deviation we have a "standard" way of knowing what is normal, and what is extra large or extra small.
#cho biết cái nào normal, cái nào extra large,cái nào extra small

#### We can expect about 68% of values to be within plus-or-minus 1 standard deviation.
##### https://www.mathsisfun.com/data/standard-deviation.html
![image-dogs](https://www.mathsisfun.com/data/images/normal-distrubution-1sd.svg)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Sorting Arrays


In [193]:
x= np.array([1,5,2,6,4,9])
np.sort(x)

array([1, 2, 4, 5, 6, 9])

In [194]:
np.argsort(x)
# hiển thị vị trí sau khi xếp

array([0, 2, 4, 1, 3, 5], dtype=int64)

In [201]:
np.random.seed(42)
MatA= np.random.randint(0,10, size=(4,6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [202]:
np.sort(MatA, axis=0) #sắp xếp theo cột tăn dần và nếu theo row thì axis=1

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra


In [204]:
a= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]
            ])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [205]:
b= np.array([[4,2],
             [4,6],
             [7,8]
            ])
b

array([[4, 2],
       [4, 6],
       [7, 8]])

In [207]:
# a(3x3) dot product b(3x2)
a.dot(b)
a@b #cách viêt khác

array([[ 33,  38],
       [ 78,  86],
       [123, 134]])

In [208]:
#nếu muốn nhân b với a (b(3x2) a(3x3))
# thì phải transpose b thành 2x3

### Dot Product example

np.random.seed(0)
sale_amounts = np.random.randint(20, size=(5,3))
sale_amounts

In [214]:
import pandas as pd
weekly_sales_df= pd.DataFrame(sale_amounts, index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                                            columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales_df

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [216]:
# create pricec array
prices= np.array([10,8,12]) # shape:(3x1)
butter_prices= pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [218]:
weekly_sales_df.shape, butter_prices.shape

((5, 3), (1, 3))

In [221]:
weekly_sales_df.shape, butter_prices.T.shape

((5, 3), (3, 1))

In [223]:
weekly_sales_df

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [224]:
butter_prices.T

Price
Almond Butter     10
Peanut Butter      8
Cashew Butter     12

In [220]:
total_prices= weekly_sales_df.dot(butter_prices.T)
total_prices

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [226]:
weekly_sales_df["Total prices"]= total_prices #thêm cột
weekly_sales_df

Almond Butter  Peanut Butter  Cashew Butter  Total prices
Mon               12             15              0           240
Tues               3              3              7           138
Wed                9             19             18           458
Thurs              4              6             12           232
Fri                1              6              7           142